# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Governor < Formula
  desc "A command cache: runs a command, caches its output for a TTL, and replays it on repeat invocations"
  homepage "https://github.com/calini/governor"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/calini/governor/releases/download/v1.0.0/governor_1.0.0_darwin_amd64.tar.gz"
      sha256 "10cc16d549f52fdc96af0e483bceafbf3597b333e4885e60972d2d87b86a91b4"

      define_method(:install) do
        bin.install "governor"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/calini/governor/releases/download/v1.0.0/governor_1.0.0_darwin_arm64.tar.gz"
      sha256 "ffe595201df52a67de01a0ac3a5a914a705165f29347c8b6084f69f46c4c365f"

      define_method(:install) do
        bin.install "governor"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/calini/governor/releases/download/v1.0.0/governor_1.0.0_linux_amd64.tar.gz"
      sha256 "8f1344205f8e3d16abbc133bf392572291e360e9f3ab750c473a3b75437aaf3b"
      define_method(:install) do
        bin.install "governor"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/calini/governor/releases/download/v1.0.0/governor_1.0.0_linux_arm64.tar.gz"
      sha256 "b8c43ac70fc3c96bd4eb21d9cd2fb9561110a1237921712d5485462ce6302980"
      define_method(:install) do
        bin.install "governor"
      end
    end
  end

  test do
    system "#{bin}/governor", "--version"
  end
end
