# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spongebob < Formula
  desc "CLI for writing SPonGeBob TeXT"
  homepage "https://github.com/calini/spongebob"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/calini/spongebob/releases/download/v0.1.0/spongebob_0.1.0_darwin_amd64.tar.gz"
      sha256 "a06f0578259d95a6eafb32c4940f26a3b105217d7171afa39f1c2a7bd94ab5cf"

      define_method(:install) do
        bin.install "spongebob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/calini/spongebob/releases/download/v0.1.0/spongebob_0.1.0_darwin_arm64.tar.gz"
      sha256 "abe9c6a0038a2178550f2f371886ca784fbf2a6241de957ca9436f4f3f35d18c"

      define_method(:install) do
        bin.install "spongebob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/calini/spongebob/releases/download/v0.1.0/spongebob_0.1.0_linux_amd64.tar.gz"
      sha256 "a4191d401c25dc507d9de6ba7349a26002ffecafd2953463d561b77e0eedf60a"
      define_method(:install) do
        bin.install "spongebob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/calini/spongebob/releases/download/v0.1.0/spongebob_0.1.0_linux_arm64.tar.gz"
      sha256 "80687a87ec421249c57d2b9475ee0269c7f3b85934f3ce26a1b1e5f5b1d3327d"
      define_method(:install) do
        bin.install "spongebob"
      end
    end
  end

  test do
    system "#{bin}/spongebob", "test"
  end
end
